services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONUSERBASE=/tmp/pip
      - PIP_USER=0

  react:
    build:
      context: ./React
      dockerfile: Dockerfile
    volumes:
      - ./React:/app
    ports:
      - "3000:3000"
    depends_on:
      - web
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata:
